# Generated by Django 3.2.10 on 2022-03-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='analyst',
            field=models.ForeignKey(blank=True,
                                    help_text='Analyst assigned to the incident',
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='incidents_assigned',
                                    to='api.person'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='color_code',
            field=models.CharField(blank=True,
                                   choices=[('gray', 'gray'), ('blue', 'blue'), ('purple', 'purple'),
                                            ('brown', 'brown')],
                                   help_text='Color code of the label',
                                   max_length=6,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time at which incident was created'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='received_at',
            field=models.DateTimeField(help_text='Time at which incident information was received', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('pre-inquiry', 'pre-inquiry'), ('in progress', 'in progress'),
                                            ('zero - inactive', 'zero - inactive')],
                                   help_text='Status of the incident',
                                   max_length=20,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subject',
            field=models.ForeignKey(help_text='Subject of the incident',
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='incidents',
                                    to='api.person'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='summary',
            field=models.CharField(blank=True, help_text='Quick summary of the incident', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time at which incident was last updated'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time at which entry was created'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name of Person', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name of Person', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time at which entry was last updated'),
        ),
    ]
